### ISSUE TITLE
Change $rootScope.$broadcast() to $rootScope.$emit()

### ISSUE THREAD

**Issue by fidian** [grevory/angular-local-storage#109]
Is there a reason that events are sent down the scope chain instead of up?  I've been playing around with angular-translate and it also sends out events but uses $rootScope.$emit().  Anyone interested in the events just use $rootScope.$on().  There's only one scope to update with the event listeners and in theory it would speed up applications.

I've even found this performance benchmark:  http://jsperf.com/rootscope-emit-vs-rootscope-broadcast

**Comment by grevory** [comment]
When I first wrote this I was very excited about signals and my tests showed that this method worked better for larger apps (particularly the one it was built for). Now, I avoid signals where possible.

This linked benchmark shows $broadcast working faster since v1.3.4. I am going to close this.
