### ISSUE TITLE
How to expire a local storage value?

### ISSUE THREAD

**Issue by blaiseliu** [grevory/angular-local-storage#133]
Is it possible to expire a value with `angular-local-storage`?

Like the way in [angular-cache][1] and [localstorage.js][2]

[1]:http://angular-data.pseudobry.com/documentation/api/angular-cache/angular-cache
[2]:https://gist.github.com/porkeypop/1096149

**Comment by matheuslc** [comment]
Can we implement this?

**Comment by eddiemonge** [comment]
Its a lot of work and since its not part of Storage spec itself, I'd say no. Wouldn't be hard to add it yourself though.

**Comment by toxaq** [comment]
Found this from @Kyoss which looks great https://gist.github.com/Kyoss79/8cd37a54679804fdeb6d
