### ISSUE TITLE
Grunt breaks LocalStorageModule

### ISSUE THREAD

**Issue by gidomanders** [grevory/angular-local-storage#183]
I'm making an application in AngularJS using Yeoman and Grunt. I implemented the LocalStorageModule and everything works fine when I use the "grunt serve" command. However, when I use the "grunt" command, the implemented modules are merged into a vendor file and uglified for safety reasons. The grunt runs fine without errors, but when opening the website I get the error: "Failed to instantiate module LocalStorageModule due to: Module 'LocalStorageModule' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.".

The thing is, I didn't do anything wrong. Something (probably in uglify) goes wrong. Any idea how I can fix this?

http://stackoverflow.com/questions/27827412/yeoman-angularjs-grunt-breaks-modules

**Comment by ohjames** [comment]
@a8m why you close this? A quick google reveals many people are having this issue, me included now.
