### ISSUE TITLE
bindToScope may should watch deep

### ISSUE THREAD

**Issue by robertaistleitner** [grevory/angular-local-storage#187]
I think that the bindToScope function should use $watch with objectEquality parameter set to true instead of $watchCollection. This would support triggering changes if editing a complex object (with nested objects in it).

Did not think of side effects in detail but I think this would be a great improvement.

So in code this means replacing
```
      scope.$watchCollection(scopeKey, function(newVal) {
        addToLocalStorage(lsKey, newVal);
      });
```
with
```
      scope.$watch(scopeKey, function(newVal) {
        addToLocalStorage(lsKey, newVal);
      }, true);
```

Looking forward to your feedback!

**Comment by a8m** [comment]
Hi @robertaistleitner, which version are you using?
check current src: [bindToScope](https://github.com/grevory/angular-local-storage/blob/master/src/angular-local-storage.js#L387-L390)

**Comment by robertaistleitner** [comment]
Hi @a8m!

Sorry about that - didn't had a look at the current version.. Was at 0.1.1..
Thanks for pointing this out!
