### ISSUE TITLE
How to switch `localStroage` to `sessionStorage` on the fly?

### ISSUE THREAD

**Issue by samrad** [grevory/angular-local-storage#192]
Based on issue #151, storage type can be set for each module but what if I want to switch the storage type inside my module? Is it possible?

The use case is, I want to implement a `remember me` functionality. If it's checked, the Authentication token will be stored on `localStorage` and if not, it'll be on `sessionStorage`.

Thanks.

**Comment by Adriien-M** [comment]
Yeah I think it will be very intersting to have two providers (localStorageServiceProvider and sessionStorageServiceProvider) to switch easily between storage modes.

**Comment by StanleyGoldman** [comment]
+1

**Comment by fvelosa** [comment]
+1

**Comment by tymondesigns** [comment]
This is possible using my storage wrapper [angular-locker](https://github.com/tymondesigns/angular-locker)

**Comment by ealves-pt** [comment]
Duplicate #181

**Comment by ealves-pt** [comment]
Duplicate #151

**Comment by ealves-pt** [comment]
Let's continue this discussion on #151
