### ISSUE TITLE
isStringNumber is not defined

### ISSUE THREAD

**Issue by chet28** [grevory/angular-local-storage#198]
Calling the localStorageService.get() errors with "isStringNumber is not defined". This happens after calling localStorageService.set('mykey', 'myvalue').

**Comment by a8m** [comment]
You should use the files inside the `dist/` directory. see: [dist](https://github.com/grevory/angular-local-storage/tree/master/dist)

**Comment by a8m** [comment]
`README` updated @chet28 , see: 93e83a3019cfb833503bfe7433602d7f43276b56
