### ISSUE TITLE
Bind to a dynamic localStorage key

### ISSUE THREAD

**Issue by varmint09** [grevory/angular-local-storage#201]
Hi,

I am creating a localStorage key for every town a user makes, like so, where app is setPrefix

```javascript
app.London
app.NewYork
```
The user can create these whilst using the Application.

Each town contains a stringified json object, and I want to sync that with $scope, so I have;
```javascript
$scope.towns = [];
$scope.towns = localStorageService.get(town);
```
That works when I refresh, but I don't want a refresh, so I want to auto-update (bind), so I have tried this;

```javascript
var townName = 'London';

localStorageService.bind($scope, 'towns', false, townName);
```

so i would expect an update to add something to app.London to trigger the above, but it doesnt, and if the user clicks a button and var townName = 'NewYork'; it doesn't fire either.

Why does the bind event not fire? Also, if I wanted the bind() to fire a function is that possible? How so?

Perhaps its worth expanding the docs around bind too?

Many thanks!

**Comment by tiagoroldao** [comment]
The bind function is one-directional, at the moment, which means while changes to your scoped model trigger changes to the localStorage, the opposite doesn't happen. At the moment, you need to refresh the scoped variable manually - `townName = 'NewYork'; $scope.towns = localStorageService.get(townName);`

**Comment by varmint09** [comment]
No worries, although I would suggest thats made clearer in the docs.  My solution ended up using $scope for the real-time updates, which is obviously a nicer solution anyway – I just needed to take a step back to realise the obvious.

- This can be closed/deleted.
