### ISSUE TITLE
angular local storage  clearAll  bug

### ISSUE THREAD

**Issue by srikondoji** [grevory/angular-local-storage#205]
We are using  v0.1.5 - 2014-11-04  angular local storage.

Our configuration looks like below, if that helps
        localStorageServiceProvider.setPrefix('Twittume');
        localStorageServiceProvider.setStorageType('sessionStorage');
        localStorageServiceProvider.setStorageCookie(30, '/');
        localStorageServiceProvider.setStorageCookieDomain('https://www.twittume.com');

The bug is, if  a user  logged out  and during logout we do local storage clear all  and then tries to
log back in, in the same browser window/tab, our application is running into issues.
However, after logging out, if we refresh the browser window/tab and log back in, our application works as expected.

Not sure, if clear all is causing an issue, preventing us to use the same browser window/tab to use for logging in. 
I can reproduce this in Firefox, Chrome and also safari.

**Comment by gnaces** [comment]
If you want to persist the login data with sessionStorage, you can't. Isn't a bug. **Session Storage** is intended to behave that way.

 Look at this. http://stackoverflow.com/questions/19867599/what-is-the-difference-between-localstorage-sessionstorage-session-and-cookie
