### ISSUE TITLE
Suggestion to allow multiple .remove()

### ISSUE THREAD

**Issue by varmint09** [grevory/angular-local-storage#207]
Hi,

If you don't want to removeAll(), why not allow .remove() to accept a comma separated list.

.remove(key1, key3, key4); // would not remove other keys, i.e key2.

Just worth suggesting I thought! Is development active?

**Comment by a8m** [comment]
LGTM.

**Comment by m00s** [comment]
Would be really helpful. Is anybody working on this?

**Comment by varmint09** [comment]
Awesome!

**Comment by a8m** [comment]
Closed via #219
