### ISSUE TITLE
Suggestion to upload lib to jsdelivr

### ISSUE THREAD

**Issue by geoperez** [grevory/angular-local-storage#210]
I found jsdelivr.com a good CDN service, can I suggest to add angular-local-storage?

Information: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

Thanks

**Comment by grevory** [comment]
@geoperez Is there a reason you closed this issue? I just created a PR with jsdelivr.

**Comment by geoperez** [comment]
Nop, I just thought was not longer a valid issue.

**Comment by geoperez** [comment]
Any news here?

**Comment by grevory** [comment]
Done and waiting for approval. Sorry for the delay. Thanks for kicking my ass on this.

**Comment by grevory** [comment]
FYI: https://github.com/jsdelivr/jsdelivr/pull/16226
