### ISSUE TITLE
isUndefined is undefined

### ISSUE THREAD

**Issue by MaxHill** [grevory/angular-local-storage#211]
Got error trying to run the save method saying isUndefined is undefined, after looking in angular-local-storage.js I found out isUndefined among others was not prefixed with angular. Prefixing the functions too ex. angular.isUndefined seams to fix it for me. Am I doing something wrong ?

**Comment by a8m** [comment]
You should use the [dist version](https://github.com/grevory/angular-local-storage/blob/master/dist/angular-local-storage.js)

**Comment by grevory** [comment]
The irony of this issue.
