### ISSUE TITLE
Thanks for the great stuff!

### ISSUE THREAD

**Issue by pairedprogrammers** [grevory/angular-local-storage#213]
We really liked using Angular Local Storage and it's made a number our projects much easier.  In fact, we liked it so much we made a tutorial video about it!  If you're interested, check it out, and feel free to add it to your documentation if you think it'll help others.  Thanks for the great project and keep up the great work everyone!

https://www.youtube.com/watch?v=I4iB0kOSmx8

**Comment by a8m** [comment]
That's great! added.
Thx.

**Comment by grevory** [comment]
Very nice video. Thanks!
