### ISSUE TITLE
Bug with booleans in .get() (so sorry)

### ISSUE THREAD

**Issue by idooo** [grevory/angular-local-storage#222]
In #220 I've introduced a bug that affected boolean values casting: string with boolean values that not in objects are not converted properly.

Eg. 
```
localStorage.set('test', true)
localStorage.get('test')  // => returns string 'true' but not boolean true
```

I've fixed that bug in this PR #221 and added test to prevent this situation in the future

**Comment by a8m** [comment]
Fixed via v0.2.1
