### ISSUE TITLE
Undesired type casting

### ISSUE THREAD

**Issue by zbysiusiekiera** [grevory/angular-local-storage#225]
Hello,

I know about #222 with primitive booleans casted to strings, but there's more:

1. String '0' is casted to number (test case with '777' works though)
2. { val: 'true' } is casted to { val: true }
3. String 'null' is casted to object

I am using angular-local-storage v0.2.0 with angular v1.3.15

**Comment by a8m** [comment]
Can you PTAL on this test cases, and confirm it fix via **v0.2.1** ?

follow your example:
1. [Numbers-like strings](https://github.com/grevory/angular-local-storage/blob/master/test/spec/localStorageSpec.js#L265-L271)
2. [Object contain boolean-like strings](https://github.com/grevory/angular-local-storage/blob/master/test/spec/localStorageSpec.js#L208-L215)
3. ['null' string](https://github.com/grevory/angular-local-storage/blob/master/test/spec/localStorageSpec.js#L249-L255)

Thanks.

**Comment by zbysiusiekiera** [comment]
Works like a charm, thank you for the fix.

**Comment by a8m** [comment]
Awesome!
Thanks.
