### ISSUE TITLE
Method "Remove", from 0.2.x v, does not return result

### ISSUE THREAD

**Issue by nenadnikolic** [grevory/angular-local-storage#226]
Method "Remove" is not returning result in case of successful removal from local storage. Following the documentation ( https://github.com/grevory/angular-local-storage#remove ) the method  should return result type boolean. Error observed starting from 0.2.0 while in 0.1.15 was working correctly.

**Comment by a8m** [comment]
Seems like this commit ea5ed1e9dbd8f45aa7e7ba3447dd0b87e97c2b06 break this behavior.
I'll try to fix it ASAP.

Thanks @nenadnikolic

**Comment by nenadnikolic** [comment]
@a8m Thank you for quick reply.

**Comment by CautemocSg** [comment]
I wanted to add that console.log(localStorageService.set(key, data)) is always returning true, even when I am sure the items are not being added to the localStorage. Not sure if this is related or not.

**Comment by Pleasurazy** [comment]
hihihi there

how is this issue going on?

Specified a bug label and closed issue, but I think the problem is still not resolve in latest version (v0.2.7)?

https://jsbin.com/himiyipaha/1/edit?js,console
