### ISSUE TITLE
How to loop on values array and pass it to api controller ?

### ISSUE THREAD

**Issue by ahmedamen** [grevory/angular-local-storage#236]
Hi

i have try to save data on Local Storage and it work and data saved as:

![untitled](https://cloud.githubusercontent.com/assets/7356190/8396290/498c66e2-1da0-11e5-9d46-b99a98180abe.png)
 
i use this code to save data:

    <script>
        var myApp = angular.module('myApp', ['LocalStorageModule']);
        myApp.controller('MainCtrl', function ($scope, localStorageService) {

            $scope.ID = '';
            $scope.SaveCustomer = function (data) {
                $scope.values = $scope.Cust;
                localStorageService.set($scope.ID, $scope.Cust);
            };

            $scope.Clear = function (data) {
                localStorageService.clearAll();
            };
        });
    </script>

but now i need to loop through all data in localStorage to get values of each key and pass them to database and pass ID to it's Filed - Name to Name Field .... ect ?

i did it with jquery and js with this code:

        function PassData() {
            var counter = 0;
            var arr = new Array();

            for (var i = 0; i < localStorage.length; i++) {
                var obj = JSON.parse(localStorage.getItem(localStorage.key(i)));

                arr[counter] = { ID: localStorage.key(i), Name: obj.Name, Age: obj.Age };
                counter++;
            }
            $.post("/api/Save", { '': arr }, function (data) {
                alert("Saved Online");
            });
        }
 but i need to know how can  i do it with angularjs - so please how can i do it .... ?

**Comment by scuba6388** [comment]
I don't see a way to get a key from an index.  I'm also curious how to loop through local storage and retrieve values.
