### ISSUE TITLE
Add feature to add an optional 3rd parameter to set to specify whether to fall back to cookie or not 

### ISSUE THREAD

**Issue by kriston13** [grevory/angular-local-storage#237]
We need a way to optionally NOT fall back to a cookie in the event that local storage is not available. We're really looking for a 3rd optional parameter in the set method - set(key, value, fallback) - that defaults to true, but can be specified to say that the cookie fallback should not be used if it would otherwise be used.

This is mostly because we sometimes want to put stuff in local storage that are more than 4k large, but if local storage isn't supported, then we don't want to try to create a cookie that is more than 4k large.

If I were to do the edit to a forked branch, would that be ok?
Thanks

**Comment by peymanebrahimi** [comment]
yes it will be very useful

**Comment by ealves-pt** [comment]
Duplicates #168

**Comment by ealves-pt** [comment]
Let's continue this discussion on #168
