### ISSUE TITLE
Change separator

### ISSUE THREAD

**Issue by furyscript** [grevory/angular-local-storage#238]
I would like to change separator from "." to "_" 
Is it possible, or is it possible to implement???

I see in source that isn't possible
https://github.com/grevory/angular-local-storage/blob/master/src/angular-local-storage.js#L82
Can you make a FIX?? :) :+1:

**Comment by varmint09** [comment]
Why would this be a fix – a full stop is the common convention?

**Comment by furyscript** [comment]
it would be nice if there was this feature!

**Comment by furyscript** [comment]
Close, I change plugin because this not support this features!
