### ISSUE TITLE
what's the usage of setNotify

### ISSUE THREAD

**Issue by warjiang** [grevory/angular-local-storage#243]
can u tell me why u user setNotify? what's the effect of setNotify function

**Comment by tylergraf** [comment]
+1

**Comment by ansballard** [comment]
Looks like setNotify has a couple boolean arguments set [here](https://github.com/grevory/angular-local-storage/blob/master/src/angular-local-storage.js#L57) that control whether `$rootscope.$broadcast(...)` is triggered when items are set or removed. This would let you use `$rootscope.$on(...)` to react when localstorageservice does something. Could be wrong, I'm just skimming the source =)

**Comment by kapusta** [comment]
To get an idea of the usage/purpose, try experimenting with these in your app.run() block or in a controller (change $rootScope to $scope in that case)...

    $rootScope.$on("LocalStorageModule.notification.setitem", function (event, data) {
      $log.log("LocalStorageModule.notification.setitem", event, data);
    });
    $rootScope.$on("LocalStorageModule.notification.removeitem", function (event, data) {
      $log.log("LocalStorageModule.notification.removeitem", event, data);
    });

You could use these to update a model in a controller after data is stored.
