### ISSUE TITLE
Events use missing from documentation

### ISSUE THREAD

**Issue by mbret** [grevory/angular-local-storage#249]
Hello I just read your doc about notify and saw that the "how to listen to event" part is missing. I think a simple part with the name of various events emitted could be fine.

**Comment by chriscohoat** [comment]
Browsing the source there are a fair number of events being broadcasted on the rootScope. To listen to notifications for set items, do something like this:

```
$scope.$on("LocalStorageModule.notification.setitem", function (event, item) {
  if (item.key === "keyBeingWatched") {
    //Do something with item...looks like: {key: "keyBeingWatched", newValue: "value", storageType: "storageType"}
  }
});
```

If you search for `$broadcast` in angular-local-storage.js you'll find the other events that can be listened to.
