### ISSUE TITLE
localstorage not sharing data between tabs

### ISSUE THREAD

**Issue by ashiefk** [grevory/angular-local-storage#252]
I have implemented localstorage in my web app configuration given below,

app.config(function (localStorageServiceProvider) {
  localStorageServiceProvider
    .setPrefix('appName')
    .setStorageType('sessionStorage')
    .setNotify(true, true)
});

and i set some data inside localstorage but when i checked in different tab (browser tabs) its returning null. Is there anything which i missed in configuration (do i need to change sessionStorage to cookie?). Is there anything i need to specify inorder to share the data between tabs? Please help !!! I really need the data between tabs just like server session.

**Comment by juliendangers** [comment]
you can't share data between multiple tabs using sessionStorage, because a new page is a new session 

see MDN https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by ashiefk** [comment]
Thank you so much, really helpful info.

**Comment by aplocher** [comment]
Is there a way to get the best of both worlds?  When the browser is closed the session no longer exists (as is the case with "sessionStorage") but while actively using the browser the user will stay logged in across tabs?  

Correct me if I'm wrong, but I think this is the type of behavior you would see using something like PHP to manage the sessions.
