### ISSUE TITLE
Values are not being set from localStorageService

### ISSUE THREAD

**Issue by amanpurohit** [grevory/angular-local-storage#258]
I am using angularjs with angular-bootstrap and I am setting the username to `localStorageService` in my `ModalInstanceController` after successful login.
`localStorageService.set('username', JSON.stringify(response.message.username));`

However sometimes the `username` is not being set to the localStorage and I am getting a `null` response. But works on multiple hard refreshes and calling of the function again and again.

**Comment by simison** [comment]
@amanpurohit what happened, did you solve this?

**Comment by amanpurohit** [comment]
Actually you need to reload the page for reading new values from localStorage or cookies.
