### ISSUE TITLE
Extra quote around stored value (v0.2.3)

### ISSUE THREAD

**Issue by armanforghani** [grevory/angular-local-storage#261]
@a8m I simply tried to set a string value by the following code:
```
localStorageService.set("key", "value");
```
In version 0.2.3 it transforms the "value" to "\"value\"".
This problem does not exist in v0.1.2.

**Comment by kabarakh** [comment]
If I see it correctly, this is because every value is transformed into a json string. While doing so with a string, the additional quotes are generated. 
But this should not be a problem, because every value is parsed from json while getting, thus removing the extra quotes again
