### ISSUE TITLE
Deploy the latest demo to http://gregpike.net/demos/angular-local-storage/

### ISSUE THREAD

**Issue by idooo** [grevory/angular-local-storage#262]
demo/demo.html was updated back in May because behaviour for .remove() was changed (https://github.com/grevory/angular-local-storage/issues/207). But it looks like those files weren't deployed so it raises issues like this: https://github.com/grevory/angular-local-storage/issues/226

To solve that problem we just need to deploy latest demo files to remote web server

**Comment by grevory** [comment]
Thanks. Updated.
