### ISSUE TITLE
Allow creating multiple instances

### ISSUE THREAD

**Issue by m-j** [grevory/angular-local-storage#270]
Restangular has similar thing. You can have your own instances of Restangular object one can be configured to hit /api onther one to hit /some-other-api.

It would be nice to have such feature here so you can use localStorage and sessionStorage simultaneously.

**Comment by JesLabs** [comment]
:+1:

**Comment by ealves-pt** [comment]
Duplicate of #181

**Comment by ealves-pt** [comment]
Let's continue this discussion on #151
