### ISSUE TITLE
iOS Low memory issue

### ISSUE THREAD

**Issue by Yngdev31** [grevory/angular-local-storage#271]
Hello,

I've a problem with LocalStorage in iOS.

I use it only for store userID, first name and name retrieved by login with Facebook (Only fews bits).

But when my memory is low, iOS delete the JSON where are store my data, and my app crash (White screen of death).

I try to do this in config.xml : 
      < preference name="BackupWebStorage" value="local" />
And this : 
      < preference name="BackupWebStorage" value="none" />

But it's not seems to work !

I just want tell to iOS "Don't delete my data !" in development language ... :smirk: 

Thanks for your time !

**Comment by simison** [comment]
This isn't an issue at the library, but how localstorage is treated at iOS Safari.

Only way to make sure your data remains at the localstorage cache, is to store it to the filesystem using [Cordova](https://cordova.apache.org/) or similar.
