### ISSUE TITLE
Support for Secure cookies?

### ISSUE THREAD

**Issue by ry8806** [grevory/angular-local-storage#272]
hi,

I've looked through the code, I can't seem to find the answer so am asking here:

Does angular-local-storage support "secure cookies", like in ngCookies (bottom of page): https://docs.angularjs.org/api/ngCookies/provider/$cookiesProvider#defaults

If not I can look at implementing

**Comment by ealves-pt** [comment]
@ry8806 I don't think it as support for that. A PR is welcome. :smiley:

**Comment by ry8806** [comment]
done in this pull request - #283 
let me know if you're happy or need any changes from me

**Comment by ealves-pt** [comment]
:+1: I will merge the PR ASAP

**Comment by ealves-pt** [comment]
Duplicates #250
