### ISSUE TITLE
import statement not working with angular-local-storage using npm & ES6

### ISSUE THREAD

**Issue by shivkumarganesh** [grevory/angular-local-storage#273]
I am trying to use  angular-local-storage using ES6 like follows:-

`import angularLocalStorage from  'angular-local-storage';`

Now I guess  angular-local-storage is not exposing a module by name. This might be the problem. Let me know if there is a possibility to contribute to the same.

**Comment by pstanisl** [comment]
It is necessary to add ```module.exports = angularLocalStorage.name;``` into ```src/angular-local-storage.js``` or ```module.exports = 'LocalStorageModule';``` into ```dist/*.js```.

There is open pull request solving the issue grevory/angular-local-storage/pull/206

**Comment by wpitallo** [comment]
Same issue tried both and neither worked

**Comment by ealves-pt** [comment]
I have a pull request, #278,  that enable to use the module with AMD and CommonJS.

**Comment by ealves-pt** [comment]
I have a PR, #277, that besides updating project's dependencies and fixing the tests also adds UMD module definition
