### ISSUE TITLE
Follow SemVer for package version

### ISSUE THREAD

**Issue by 0x2206** [grevory/angular-local-storage#293]
First of all thank you for your awesome package! We are using it in our projects and we are very pleased with it.

Although, I see there's some space for improvements in terms of versioning. What do you think about following Semantic Versioning to make world a better place? That would really help with dependencies resolution, automation like CI/CD and quality assurance in general.

Some useful resources:

- http://semver.org/
- https://github.com/semantic-release/semantic-release

**Comment by simison** [comment]
https://github.com/grevory/angular-local-storage/issues/289

**Comment by ealves-pt** [comment]
@0x2206 thank you for your input. Yes we are following semver but with our last release I underestimate the impact of the changes. I will pay more attention in the future to avoid this kind of situations. :+1:
