### ISSUE TITLE
In Safari on iPhone and iPad method keys() return undefined

### ISSUE THREAD

**Issue by Sharykhin** [grevory/angular-local-storage#295]
There is method keys() and according to your description it returns keys from local storage. But because on iPhone and iPad Safari is under private mode, local storage is not available and as a result this method returns undefined. I don't wanna say that this is a bug, but instead of returning undefined, why don't you return an empty array, for example. I got in trouble because I used indexOf right after localStorageService.keys()
It's not an obvious error, so, I hope will help others to get away from this potenrial error

**Comment by vwochnik** [comment]
This is a handy syntax for such cases:

```
var keys = localStorageService.keys() || [];
```
