### ISSUE TITLE
Quota Exceeded Error

### ISSUE THREAD

**Issue by AbuSufyan** [grevory/angular-local-storage#298]
Thanks for your valuable contribution for such nice angular local storage. Currently you are using WebStorage behind this. We work on financial application and we use session Storage, Its working fine upto 3 keys and our every key contains data around 1.75 MB, we got exception 'QuotaExceededError'  when we set data more than 3 keys and our data size increased from 5 MB's. I searched on the Internet and find that the WebStorage limited to 5 MB in Internet Explorer version 11. How we increase that limit upto 50 MB and fix that issue? Its very important for us.

**Comment by ealves-pt** [comment]
As far as I know there is nothing you can do to change that.

**Comment by grevory** [comment]
It is a browser limitation. I believe some browsers are different, but from my research when I created this module 5MB is the lowest common denominator.
