### ISSUE TITLE
Clear All

### ISSUE THREAD

**Issue by mshref17** [grevory/angular-local-storage#299]
Hi,

I am clearing my localstorage object but scope is not cleared.

am I missing something, or you have a bug with this? I am not using cookies

**Comment by grevory** [comment]
Clear All wouldn't do anything to your scope. You would need to update your own scope.

I presume you are referring to Angular scope.

**Comment by sahilbabbar** [comment]
@grevory So, if we bind ```localStorageService``` to ```$scope```, then, it should work, right?
