### ISSUE TITLE
Question: How angular-local-storage works in IE10?

### ISSUE THREAD

**Issue by JulioDeL** [grevory/angular-local-storage#309]
Hello,

I need to add local storage to my Angular app. I have read many posts to document myself before picking a module and **angular-local-storage** seems to be fairly well rated. But I wonder how it works in IE10, because, according to caniuse, that IE version does not support local storage:

http://caniuse.com/#feat=namevalue-storage

I know there is the cookie fall back alternative, but I'm curious what would happen if I use `localStorageService.set` or `localStorageService.get`methods in IE10. Would that break the app?

Thanks

**Comment by grevory** [comment]
IE10 supports local storage. On caniuse.com click "Show All."

Also, even if it did not support local storage it will store the data in cookies using the same API. localStorageService setters and getters will store and get from whatever storage option is available. The whole idea is that it's seamless for you to develop.
