### ISSUE TITLE
Store string with double-double quotes

### ISSUE THREAD

**Issue by stunaz** [grevory/angular-local-storage#311]
Hi, When I inspect my local storage in firefox , I see that string value are saved with double-double quotes i.e. `language :""en""`

Altrought the retrieval is fine, I found this weird.

**Comment by jgpacheco** [comment]
Yes, these extra double-quotes make this code fail in my app.

`            $window.addEventListener('storage', function (event) {
                if (event.newValue === 'somestring') {
                  //
                }
}`
