### ISSUE TITLE
What is the Capacity of angular-local-storage?

### ISSUE THREAD

**Issue by priyanka-obtainit** [grevory/angular-local-storage#323]
What is the maximum limit of data I can store in this local storage. Also will it affect the performances of web app if I hold large amount of data in local storage?

**Comment by grevory** [comment]
There is no limit for angular-local-storage. The limit is with the browser and browsers set arbitrary limits. There is an error you can listen for when a limit is exceeded.

**Comment by priyanka-obtainit** [comment]
So I want to hold more than 60 key value pairs and also the array in single local-storage veriable.
will it create any problem?

**Comment by grevory** [comment]
The number of keys is not the limiting factory. Go to town.

**Comment by priyanka-obtainit** [comment]
I am new to angular. So I don't know how and which factors affect the performances of the angular application. I am holding large amount of data in single page through multiple angular controller in $scope and in this local storage. So is it a good choice?

**Comment by grevory** [comment]
The more data you store the more memory will be required by the browser. Local storage is handled by the browser so there is trivial performance loss by access local storage data over local data. Anything more than that is going to require some research on your end. Not really something I can go over in a comment. Best of luck.

**Comment by priyanka-obtainit** [comment]
Ok. Thanks.
