### ISSUE TITLE
Unknown provider: localStorageService

### ISSUE THREAD

**Issue by lsantaniello** [grevory/angular-local-storage#329]
Hi guys,
I receive "Unknown provider: localStorageService" when I inject the service. I use it for ionic application.

`angular.module('starter', ['LocalStorageModule'])`

`  .config(function (localStorageService, localStorageServiceProvider) {
    localStorageServiceProvider.setPrefix("starter");
    localStorageServiceProvider.setStorageType('localStorage');
  })`

`  .controller('MenuCtrl', function ($scope, localStorageService) {

    if (localStorageService.isSupported) {
      console.log("Local Storage supported");
    } else {
      console.log("WARNING!!! Local Storage not supported");
    }
  })`

Can you support me please?

Thanks a lot

Luca

**Comment by grevory** [comment]
You should remove "localStorageService." Good luck!

**Comment by grevory** [comment]
Did everything work out for you after? Would like to close this issue. Thanks.
