### ISSUE TITLE
Null key

### ISSUE THREAD

**Issue by daviferreira** [grevory/angular-local-storage#330]
We just got this error recently:

```
TypeError: Cannot read property 'indexOf' of null

angular-local-storage/dist/angular-local-storage.js", line 120
            return key.indexOf(prefix) === 0;
```

Wasn't able to reproduce it yet, but I'm guessing it is related to this commit: https://github.com/grevory/angular-local-storage/commit/517cc4d48488b24b003600f1645e2c0d539ada41

**Comment by grevory** [comment]
Good catch. We should do string checking for keys before performing string operations.
