### ISSUE TITLE
Invalid character at the end of file

### ISSUE THREAD

**Issue by nalepek** [grevory/angular-local-storage#334]
Hi!

I just included an angular-local-storage in my app, and whole time I get an error "invalid character" at the end of the file.

I really don't know what is going, because there aren't any characters after ending colon ;

Can anyone had this issue also?

Any help will be appreciated.

**Comment by grevory** [comment]
I do not think this is a problem with the Angular Local Storage module. Can you post how you have the module set up?

**Comment by nalepek** [comment]
I've found the problem.
I've copied the angular-local-storage.js from dist folder from RAW. At the end of the file there were few invisible characters which I can't see in my .js file. When I copied the whole text into the Word and turned in the formatting marks I saw few invisible characters. I deleted them, copied to my .js file and problem solved! :)

**Comment by grevory** [comment]
Thanks for the update
