### ISSUE TITLE
how to share the data in multiple tabs, but also need clear after closing the browser

### ISSUE THREAD

**Issue by hank-hong** [grevory/angular-local-storage#337]
Hello,

I found if I used localstorage, the data will always be saved even though I closed the browser.
Buf if I use sessionstorage, the data won't be shared in multiple tabs.

Could you please give me some suggestion? 
Thanks

**Comment by daredevil82** [comment]
You can detect the JS `onunload` and `onbeforeunload` events, and then fire a `localStorageService` clear call.

http://stackoverflow.com/questions/30345446/how-to-trigger-a-function-on-window-close-using-angularjs has more details for this.
