### ISSUE TITLE
LocalStorageService across subdomains?

### ISSUE THREAD

**Issue by LurchUSA** [grevory/angular-local-storage#341]
Is is possible to have the values stored in the localStorageService, so be accessible across subdomains?

For example.

companydomain.com
product.companydomain.com
service.companydomain.com

If you have a single signon page in companydomain.com, I want to save the authenticated user details within the localStorageService.

Now if I navigate from companydomain.com to one of the two subdomains (ie. product.companydomain.com or service.companydomain.com) I want to be able to access the data stored in the localStorageService, that was set back in  companydomain.com.

I know this is not possible if the domains are entirely different (eg. companydomain.com -> anothersite.com), however I have seen some examples of setting the document.domain value to the parent domain, which allows access to those values in the subdomain.

Can this be applied to angular-local-storage?

**Comment by grevory** [comment]
There is a way to do this but it is a hack. I am not sure it is something the module should do by default. You could try using the solution outlined here: https://stackoverflow.com/questions/4026479/use-localstorage-across-subdomains
