### ISSUE TITLE
Set pair key/value with type method setting type of storage.

### ISSUE THREAD

**Issue by JoseCMRocha** [grevory/angular-local-storage#348]
Right now there is a possibility to on set define the storage type where we want to add our pair key/value.

This at the moment is implemented in a way that it sets globally the storage type in use. For example if I have a instance of the angularLocalStorage using the storage type 'localStorage' and I make a call like '.set('boo', 'foo', 'sessionStorage'), the storage type will be changed to 'sessionStorage' automatically.  

Is this intended? in my point of view when calling '.set('boo', 'foo', 'sessionStorage') it should add the pair to the session storage but the storage in use should continue to be the local storage, and only be possible to change the storage type in use calling the method 'setStorageType'.

**Comment by grevory** [comment]
There is a PR I am just about ready to merge in. Check out https://github.com/grevory/angular-local-storage/pull/344
