### ISSUE TITLE
using both sessionStorage and localStorage

### ISSUE THREAD

**Issue by oreillyj1** [grevory/angular-local-storage#350]
Hi 
great framework by the way ...I'm using angular1 and have found this framework really useful.

**BUT**: maybe I'm missing something....but can i add to the session Storage while also adding to the local storage using this framework? 
Is there is an option to specify if the data item is to be saved as local or session at the moment?..if there is would a example be out there on the web using both?

**Comment by grevory** [comment]
I think this issue is covered in #344
