### ISSUE TITLE
isSupported not working

### ISSUE THREAD

**Issue by colinbes** [grevory/angular-local-storage#88]
I've been messing around with this module in a small project using node, express and angular and noticed that the isSupported function doesn't work. 

In library function browserSupportsLocalStorage, should line 
```
var supported = (storageType in $window && $window[storageType] !== null);
```
not read 
```
var supported = ("localStorage" in $window) && ($window['localStorage'] !== null)
```

i.e. referencing item 'localStorage' and not 'storageType'

I see in code that storageType should be defaulting to 'localStorage' so above should work - I'm not sure what's up.

**Comment by ealves-pt** [comment]
Fix was added.
