### ISSUE TITLE
solved: browserSupportsLocalStorage returns wrong value in IE7

### ISSUE THREAD

**Issue by pbastowski** [grevory/angular-local-storage#90]
Hi, just fixed a bug in the function browserSupportsLocalStorage around line 99. Below is a snippet of code. Sorry, I didn't have time to create a pull-request, but thought someone might find the fix useful too.

```
        if (supported) {
          webStorage.setItem(key, '');
          webStorage.removeItem(key);
        }

        return supported;
```

In your code you return True, but it should return the value in the variable "supported" instead, as per above.

**Comment by ealves-pt** [comment]
Fix was added.
